#ifndef GUY_METASPRITES_H
#define GUY_METASPRITES_H

#include <snes.h>

#define _G (OBJ_PAL(0) | OBJ_PRIO(3))

// 64x96 metasprite made from twenty-four 16x16 OBJ sprites.
// oamMetaDraw16 expects sequential 16x16 object indexes, like the
// metasprite .inc files generated by gfx4snes -T.
static const t_metasprite guyMetasprite[] = {
    METASPR_ITEM(0, 0, 0, _G),    METASPR_ITEM(16, 0, 1, _G),
    METASPR_ITEM(32, 0, 2, _G),   METASPR_ITEM(48, 0, 3, _G),

    METASPR_ITEM(0, 16, 4, _G),   METASPR_ITEM(16, 16, 5, _G),
    METASPR_ITEM(32, 16, 6, _G),  METASPR_ITEM(48, 16, 7, _G),

    METASPR_ITEM(0, 32, 8, _G),   METASPR_ITEM(16, 32, 9, _G),
    METASPR_ITEM(32, 32, 10, _G), METASPR_ITEM(48, 32, 11, _G),

    METASPR_ITEM(0, 48, 12, _G),  METASPR_ITEM(16, 48, 13, _G),
    METASPR_ITEM(32, 48, 14, _G), METASPR_ITEM(48, 48, 15, _G),

    METASPR_ITEM(0, 64, 16, _G),  METASPR_ITEM(16, 64, 17, _G),
    METASPR_ITEM(32, 64, 18, _G), METASPR_ITEM(48, 64, 19, _G),

    METASPR_ITEM(0, 80, 20, _G),  METASPR_ITEM(16, 80, 21, _G),
    METASPR_ITEM(32, 80, 22, _G), METASPR_ITEM(48, 80, 23, _G),

    METASPR_TERM
};

static const t_metasprite guyMetaspriteFlip[] = {
    METASPR_ITEM(48, 0, 0, _G | OBJ_FLIPX),
    METASPR_ITEM(32, 0, 1, _G | OBJ_FLIPX),
    METASPR_ITEM(16, 0, 2, _G | OBJ_FLIPX),
    METASPR_ITEM(0, 0, 3, _G | OBJ_FLIPX),

    METASPR_ITEM(48, 16, 4, _G | OBJ_FLIPX),
    METASPR_ITEM(32, 16, 5, _G | OBJ_FLIPX),
    METASPR_ITEM(16, 16, 6, _G | OBJ_FLIPX),
    METASPR_ITEM(0, 16, 7, _G | OBJ_FLIPX),

    METASPR_ITEM(48, 32, 8, _G | OBJ_FLIPX),
    METASPR_ITEM(32, 32, 9, _G | OBJ_FLIPX),
    METASPR_ITEM(16, 32, 10, _G | OBJ_FLIPX),
    METASPR_ITEM(0, 32, 11, _G | OBJ_FLIPX),

    METASPR_ITEM(48, 48, 12, _G | OBJ_FLIPX),
    METASPR_ITEM(32, 48, 13, _G | OBJ_FLIPX),
    METASPR_ITEM(16, 48, 14, _G | OBJ_FLIPX),
    METASPR_ITEM(0, 48, 15, _G | OBJ_FLIPX),

    METASPR_ITEM(48, 64, 16, _G | OBJ_FLIPX),
    METASPR_ITEM(32, 64, 17, _G | OBJ_FLIPX),
    METASPR_ITEM(16, 64, 18, _G | OBJ_FLIPX),
    METASPR_ITEM(0, 64, 19, _G | OBJ_FLIPX),

    METASPR_ITEM(48, 80, 20, _G | OBJ_FLIPX),
    METASPR_ITEM(32, 80, 21, _G | OBJ_FLIPX),
    METASPR_ITEM(16, 80, 22, _G | OBJ_FLIPX),
    METASPR_ITEM(0, 80, 23, _G | OBJ_FLIPX),

    METASPR_TERM
};

#endif // GUY_METASPRITES_H
